services:
  mysql:
    build:
      context: ../../docker/mysql
      dockerfile: Dockerfile
    container_name: cdc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DB:-cdcdb}
      MYSQL_USER: ${MYSQL_USER:-cdcuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-cdcpass}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpass}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cdc-network
