services:
  postgres:
    build:
      context: ../../docker/postgres
      dockerfile: Dockerfile
    container_name: cdc-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cdcuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cdcpass}
      POSTGRES_DB: ${POSTGRES_DB:-cdcdb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-cdcuser}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cdc-network
