services:
  loki:
    image: grafana/loki:latest
    container_name: cdc-loki
    ports:
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - ../../docker/observability/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cdc-network
