# Order Schema Definition
table_name: orders
description: Order data schema for CDC demo

fields:
  - name: order_id
    type: SERIAL
    primary_key: true
    description: Unique order identifier

  - name: customer_id
    type: INTEGER
    nullable: false
    foreign_key:
      table: customers
      column: customer_id
    description: Reference to customer

  - name: order_date
    type: TIMESTAMP
    default: CURRENT_TIMESTAMP
    faker_method: date_time_between
    faker_args:
      start_date: "-30d"
      end_date: "now"
    description: Order placement date

  - name: total_amount
    type: DECIMAL(10,2)
    nullable: false
    faker_method: pydecimal
    faker_args:
      left_digits: 4
      right_digits: 2
      positive: true
      min_value: 10
      max_value: 10000
    description: Total order amount

  - name: status
    type: VARCHAR(50)
    default: pending
    enum: [pending, processing, shipped, delivered, cancelled]
    description: Order status

  - name: shipping_address
    type: TEXT
    nullable: true
    faker_method: address
    description: Shipping address

  - name: created_at
    type: TIMESTAMP
    default: CURRENT_TIMESTAMP
    description: Record creation timestamp

  - name: updated_at
    type: TIMESTAMP
    default: CURRENT_TIMESTAMP
    description: Record last update timestamp

indexes:
  - name: idx_orders_customer_id
    columns: [customer_id]

  - name: idx_orders_status
    columns: [status]

generation_rules:
  default_count: 5000
  batch_size: 500
  depends_on: [customers]
