services:
  minio:
    image: minio/minio:latest
    container_name: cdc-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cdc-network

  minio-init:
    image: minio/mc:latest
    container_name: cdc-minio-init
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ../../docker/minio/init-buckets.sh:/init-buckets.sh:ro
    entrypoint: /bin/sh
    command: /init-buckets.sh
    networks:
      - cdc-network
