services:
  cdc-init:
    build:
      context: ../..
      dockerfile: docker/cdc-init/Dockerfile
    container_name: cdc-init
    depends_on:
      debezium:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      iceberg-rest:
        condition: service_healthy
    volumes:
      - ../../scripts:/app/scripts:ro
      - ../../src:/app/src:ro
      - ../../.env:/app/.env:ro
      - delta_tables:/tmp/delta
      - iceberg_warehouse:/tmp/iceberg_warehouse
      - spark_checkpoints:/tmp/spark-checkpoints
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DEBEZIUM_HOST=debezium
      - DEBEZIUM_PORT=8083
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=cdcuser
      - POSTGRES_PASSWORD=cdcpass
      - POSTGRES_DB=cdcdb
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=cdcuser
      - MYSQL_PASSWORD=cdcpass
      - MYSQL_DB=cdcdb
    command: bash scripts/infrastructure/init-all.sh
    restart: unless-stopped
    networks:
      - cdc-network
    deploy:
      resources:
        limits:
          memory: ${SPARK_MEMORY_LIMIT:-2g}
          cpus: '${SPARK_CPU_LIMIT:-1.0}'
